//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Project_JJEZ57
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termek
    {
        public int Id { get; set; }
        public string Nev { get; set; }
        public Nullable<int> Darab { get; set; }
        public Nullable<int> Egységár { get; set; }
    }
}
